In [1]:
import numpy as np

# arrayの作り方

In [2]:
#numpyのarrayを作るにはlistを使うのが一番かんたん
my_list1 = [1,2,3,4]
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [3]:
#多次元配列（2行4列）
my_list2 = [11,22,33,44]
my_lists = [my_list1,my_list2]
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [4]:
#何行何列か確認
my_array2.shape

(2, 4)

In [5]:
#datatypeの確認
#arrayは要素が全て同じ型でなければいけない
my_array2.dtype

dtype('int64')

In [6]:
#特殊なアレイ
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
#要素が全て1
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#値を0や1で初期化する必要のない時の生成のしかた
np.empty((3,4))

array([[-2.00000000e+000, -3.11108086e+231,  2.96439388e-323,
         0.00000000e+000],
       [ 2.37663529e-312,  8.75983079e+164,  5.00230827e-090,
         9.90700541e+164],
       [ 1.55113123e+184,  3.99840215e+175,  3.99910963e+252,
         8.34402697e-309]])

In [9]:
#単位行列
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
#範囲を指定してarrayを生成
#range()の使い方と似ている
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

# arrayを使った計算

In [12]:
arr1 = np.array(([1,2,3,4],[8,9,10,11]))
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

# 四則演算

In [13]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [14]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
#array同士でなくても計算可能
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [16]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

# arrayの添字

In [17]:
arr = np.arange(0,11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr[8]

8

In [20]:
arr[1:5]

array([1, 2, 3, 4])

In [21]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [22]:
#0~5まで100を代入
arr[0:5] = 100

In [23]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

## arrayは参照でしかないので元のデータも変更される

In [24]:
arr = np.arange(0,11)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
slice_arr = arr[0:6]

In [27]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [28]:
slice_arr[:] = 99

In [29]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [30]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
#元のarrayを変更しないようにするためには.copyを使う

In [32]:
arr_copy = arr.copy()

In [33]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [34]:
arr_copy[:] = 50

In [35]:
arr_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [36]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## 2次元のarrayの添字

In [37]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [38]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[0]

array([ 5, 10, 15])

In [40]:
arr_2d[1][0]

20

In [41]:
#上と同義
arr_2d[1,0]

20

In [42]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [44]:
arr_2d[2]

array([35, 40, 45])

In [45]:
arr_2d[2,:]

array([35, 40, 45])

In [46]:
arr_2d[:,2]

array([15, 30, 45])

In [47]:
arr2d = np.zeros((10,10))

In [48]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
#arrayの長さを変数に格納(タプルなので0,1で行or列の指定が可能。今回は1なので列)
arr_length = arr2d.shape[1]

In [50]:
#forで
for i in range(arr_length):
    arr2d[i] = i

In [51]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [52]:
#添字にlistを与えると指定した行のみを取り出すことができる
#順番が違くても大丈夫（例：[6,8,3,4]など）
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [53]:
arr2d[[6,8,3,4]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

# 行と列の入れ替え

In [54]:
arr = np.arange(9).reshape((3,3))

In [55]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
#転置
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [57]:
#上と同義
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [58]:
#0が行1が列
arr.transpose((0,1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
arr.transpose((1,0))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [60]:
#swapaxesというメソッドもあるが基本的にはTかtransposeを使う

In [61]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [62]:
#行列の掛け算 dotメソッドで計算
np.dot(arr.T, arr)

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

## 3次元でも行と列の入れ替えは可能

In [63]:
#2*2の行列が3つある状態（要素が3つ）
arr3d = np.arange(12).reshape((3,2,2))
arr3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [64]:
arr3d[0]

array([[0, 1],
       [2, 3]])

In [65]:
arr3d.transpose((0,2,1))

array([[[ 0,  2],
        [ 1,  3]],

       [[ 4,  6],
        [ 5,  7]],

       [[ 8, 10],
        [ 9, 11]]])

In [66]:
#3次元の行と列の入れ替えは複雑なのでTとtransposeで入れ替えができることが分かればOK

# アレイと計算のための関数

In [67]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
#各要素の平方根の計算
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [69]:
#eの冪乗の計算（要素が指数になる）
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [70]:
#正規分布に従ってランダムに値を選んでarrayを作る
A = np.random.randn(10)
A

array([ 0.18478563,  2.64282914,  1.27056021,  2.1561564 ,  1.12090101,
        0.89980662, -1.56549128,  0.966741  , -2.78745305,  0.68253996])

In [71]:
B = np.random.randn(10)
B 

array([-1.90719613,  1.34629304, -1.04187666,  0.85398315, -1.25130509,
       -0.17645576,  0.91867648,  0.29374595,  2.19449676,  1.65493578])

In [72]:
#array同士の足し算
np.add(A,B)

array([-1.72241049,  3.98912218,  0.22868355,  3.01013955, -0.13040408,
        0.72335086, -0.6468148 ,  1.26048695, -0.59295628,  2.33747574])

In [73]:
#各要素の大きい方を計算
np.maximum(A,B)

array([0.18478563, 2.64282914, 1.27056021, 2.1561564 , 1.12090101,
       0.89980662, 0.91867648, 0.966741  , 2.19449676, 1.65493578])

In [74]:
#numpyの計算を全て覚えるのは難しいのでHelpからnumpyのreferenceをみると良い